atuinsh/docs

src/content/docs/uninstall.md
I'm not sure how helpful this is, as it's basically just "it depends"
=> docs: add uninstall

src/content/docs/self-hosting/docker.mdx
Take 2 https://github.com/atuinsh/atuin/pull/1541
For what it's worth, I wrote up my full notes here: https://notes.billmill.org/computer_usage/atuin/self-hosting_atuin.html
I found a lot of that not in the docs; maybe that page will be useful in terms of what could go in here
=> docs: docker-compose -> docker compose

astro.config.mjs, src/content/docs/guide/sync.mdx, src/content/docs/self-hosting/server-setup.mdx, src/content/docs/self-hosting/usage.mdx
I had some trouble finding out how to use my self-hosted server rather than the one provided by Atuin. Hoping to clarify that a bit using this PR.
=> Clarify usage of self hosted servers

src/content/docs/configuration/config.mdx
This is an update to the documentation in accord with https://github.com/atuinsh/atuin/pull/1570.
=> docs(config)!: update config "vim => keymap_mode"

src/content/docs/guide/sync.mdx
Ran into this while browsing the docs.
=> Fix broken link to sync configuration

src/content/docs/reference/import.mdx
This was fairly incomplete. Everything probably *just works* for most people, but I figured it was good to have all of this documented for when it doesn't.
=> Add details about where each importer looks for data

src/content/docs/guide/getting-started.mdx, src/content/docs/guide/installation.mdx, src/content/docs/index.mdx
This adds xonsh-related informations to the docs.
Related PR: https://github.com/atuinsh/atuin/pull/1375
=> Add xonsh to docs

src/content/docs/configuration/config.mdx
I noticed an inconsistency in the formatting for property names, where some where using code format and some not. 
Changed all to use code format.
=> Small formatting change.

src/content/docs/configuration/config.mdx
ref: https://github.com/atuinsh/atuin/pull/1645
=> docs: no motion

src/content/docs/configuration/config.mdx, src/content/docs/reference/prune.mdx
Document the new feature added with https://github.com/atuinsh/atuin/pull/1743
=> Add docs for the prune subcommand

package-lock.json, package.json, src/content/docs/guide/installation.mdx
Mostly restructuring and rephrasing, see commit messages for details.
Upgraded Astro/Starlight dependencies in order to get `<Aside>` support, which allows displaying warnings by using MDX components.
Breaking changes: Please do note that some headings were changed. This may cause page anchors to break. I don't expect this to be much of an issue, as the doc is quite compact anyway.
=> Onboarding UX: Installation guide

src/content/docs/configuration/config.mdx
Add dotfiles to configuration options page
=> docs: document dotfiles

src/content/docs/configuration/config.mdx
Corresponding docs for https://github.com/atuinsh/atuin/pull/1957
**Assumes next release is v18.3.0**
=> document store_failed config option

astro.config.mjs, src/content/docs/self-hosting/docker.mdx, src/content/docs/self-hosting/systemd.mdx
Part of https://github.com/atuinsh/atuin/issues/1864.
=> Add Systemd config for self-hosted server

src/content/docs/configuration/key-binding.mdx, src/content/docs/reference/search.md
One to add the delete command after opening inspector.
Second an attempt  to make the table look nice.
=> Two trivial doco changes

src/content/docs/configuration/config.mdx
Docs update for https://github.com/atuinsh/atuin/pull/2174
=> update docs to reference new secrets patterns

.gitignore, src/content/docs/configuration/config.mdx
Few updates and improvements to the configuration file focused in page formatting:
- Adjust the general formatting of the configuration page to improve readability and consistency.
- Set a standard for the "Default" value of each option in the file to ensure uniformity.
- Applied `toml` syntax highlighting to code blocks that were previously missing it, making the code examples clearer and easier to read.
=> chore:·update·configuration·file·formatting·and·standardization

src/content/docs/guide/installation.mdx
The details are explained in the commit messages.
=> docs(installation): update descriptions for Bash

src/content/docs/configuration/config.mdx
Docs update for https://github.com/atuinsh/atuin/pull/2210
=> Update docs for new secret patterns

src/content/docs/guide/installation.mdx
zinit can also download and extract from gh-releases
=> doc(installation): extend zinit options

astro.config.mjs, src/content/docs/configuration/config.mdx, src/content/docs/guide/theming.mdx
Aligns with https://github.com/atuinsh/atuin/pull/2236 to explain the usage of themes.
TODO: Markdown needs to be checked, but here for feedback initially.
More information is available at that PR.
=> Draft: adds docs for theming

src/content/docs/configuration/config.mdx
Documentation update for atuinsh/atuin#2286
=> Docs for atuinsh/atuin#2286

astro.config.mjs, package-lock.json, package.json
This makes it easier to e.g. reference particular atuin config keys in the documentation.
Preview:
=> feat(config): create anchor links for headings

src/content/docs/configuration/config.mdx
=> fix: typo in secrets_filter section

src/content/docs/guide/installation.mdx
Details are described in the commit message.
=> docs(installation): add missing version requirement for `ble.sh`
