src/content/docs/configuration/config.mdx

This describes config `keymap_cursor` added in https://github.com/atuinsh/atuin/pull/1595.
Let me also add typo fixes to my previous PR #8 in commit a823801.

docs(config): describe config `keymap_cursor`

---

src/content/docs/configuration/config.mdx
src/content/docs/configuration/key-binding.mdx

Commit b8c6b9a corresponds to the widget name change introduced in https://github.com/atuinsh/atuin/pull/1631. Also, the current documentation diverges from the current implementation. I updated the widgets for the <kbd>up</kbd> key in commit 6e1f3df. Also, the descriptions for the newly added widgets for `keymap_mode` (https://github.com/atuinsh/atuin/pull/1570) are added in commit 705214a.
Since the version dependence of documentation can confuse people as in https://github.com/atuinsh/atuin/issues/1625, I decided to add a note on the version dependence and also a required version for each feature. I personally think it is useful to maintain in the documentation the minimal version requirement for each feature, but this might be the perspective of a developer who needs to consider the …

docs(key-bindings): update widget descriptions

---

package-lock.json
src/content/docs/self-hosting/docker.mdx

Also bumps the version of vite since it was flagged for a security
issue.
Probably needs the same info added for Kubernetes, but I'm not really
familiar with that. :/

Add infos on how to backup self-hosted DB

---

src/content/docs/configuration/config.mdx

This PR fixes reference to `stats` subcommand documentation to point to the correct file.

Fix referene to stats documentation

---

src/content/docs/self-hosting/kubernetes.mdx

TLDR: The postgres hosting described may to corruption of the DB. This PR updates to try and make this less likely.
Ps. Not a postgres expert, did [some reading](https://stackoverflow.com/questions/75828221/how-to-safely-restart-postgresql-container-in-kubernetes/75829325#75829325) after corrupting my DB in k8s. 
The current docs suggest hosting the `postgres` as a sidecar to the atuin container.
This means:
1. Updates to `atuin` results in restart of the `postgres` container. 
1. Crashes in `atuin` cause not only `atuin` to restart but also `postgres`
1. The `Strategy` for the `Deployment` default to [`RollingUpdate`](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) so a new pod is brought up before the old one is stopped
When updating atuin we therefor end …

K8s: Make Postgres hosting safer

---

src/content/docs/reference/import.mdx

Documentation for Xonsh importers, as discussed in atuinsh/atuin#1678 and atuinsh/atuin#1711.
I also noticed that the TOC wasn't generating properly on the page, so I changed the h1's to h2's and that seems to have fixed it. This does slightly change the appearance of the page, so I'm happy to revert that if you'd prefer to keep it the way it was.

Add documentation for Xonsh import

---

src/content/docs/configuration/config.mdx
src/content/docs/configuration/key-binding.mdx

Also, the description of a missing config `local_time` was added, and the minimum version requirements for the recently added configs were added.

docs(configuration): update version information 

---

src/content/docs/configuration/key-binding.mdx

Just a small link update for saving me time trying to figure out which setting was it referring to. I hope I selected the right setting (tested it though, seems to be the right one). :)

Add link to exit_mode setting for down-arrow

---

astro.config.mjs
package-lock.json
package.json

Noticed there was a plugin for Astro Starlight for internal link validation, figured it would be useful to have in the project. Documentation can be found here: https://starlight-links-validator.vercel.app. Only runs for production builds.

Add internal link validation using Starlight Links Validator

---

.github/workflows/deploy.yml

The checkout action is using an older version of checkout, triggering a deprecation warning here: https://github.com/atuinsh/docs/actions/runs/7986293151.

Update checkout action to fix node deprecation warning

---

src/content/docs/configuration/config.mdx

I've been using atuin on my Linux box for some time now and I have noticed that a few commands that are used rather often are not in the list of common_subcommands.

docs(stats): add more linux sysadmin commands to common_subcommands

---

src/content/docs/configuration/key-binding.mdx

This updates the docs in case https://github.com/atuinsh/atuin/pull/1770 lands, which fixes the referenced issue https://github.com/atuinsh/atuin/issues/1025
Since this hasn't happened yet I created this as a draft - feel free to un-draft it!

docs: remove outdated note on nushell keybindings

---

src/content/docs/reference/gen-completions.mdx

Updates docs to reflect changes from https://github.com/atuinsh/atuin/pull/1791

docs: add nushell to gen-completion shell list

---

src/content/docs/configuration/config.mdx

The command to create a new alias is `autin dotfiles alias set`, not `atuin dotfiles alias create`

Fix atuin dotfiles alias command example

---

src/content/docs/configuration/config.mdx

I wasn't able to add the version info, since I didn't know when this will be available: `18.0.2`, `18.0.3`, `18.1.0`, ...
Btw, I've also noticed that the `[sync]` section and the `records` option is missing from the docs.

docs: add keys section and scroll_exits option

---

src/content/docs/reference/list.mdx

The description makes it sound like it takes an argument, but it is a [boolean](https://github.com/atuinsh/atuin/blob/82a7c8d3219749dd298b23bae22456657ee92575/atuin/src/command/client/history.rs#L48-L51) and gets mad when you try to give it one. I also updated the `--session` description so they have matching sentence structure.

Fix `--cwd` description on history list command

---

src/content/docs/self-hosting/docker.mdx

Rather than expecting people to figure out where the recent releases are, just link them :D

Add links to the GitHub releases for docker instructions

---

src/content/docs/self-hosting/docker.mdx

In the example Dockerfile, the value of `ATUIN_DB_NAME` currently isn't passed through to the atuin service.

Use $ATUIN_DB_NAME in URL in example

---

src/content/docs/configuration/key-binding.mdx

This documents keybindings mentioned in https://github.com/atuinsh/atuin/issues/592

Docs: Add inspector view keybindings

---

src/content/docs/configuration/config.mdx

It seems that the next release will be `18.3.0`.
This section of the client config is specifically for configuring preview-related settings.
(In the future the other 2 preview settings will be moved here.)
```
[preview]
strategy = [...]
```
Atuin version: >= 18.3
Which preview strategy is used to calculate the preview height. It respects `max_preview_height`.
| Value          | Preview height is calculated from the length of the |
|----------------|-----------------------------------------------------|
| auto (default) | selected command                                    |
| static         | longest command in the current result set           |
By using `auto` a preview is shown, iff the command is longer than the width of the terminal.

add docs for show_preview_auto

---

src/content/docs/configuration/key-binding.mdx

I hated the default `enter` key behavior but changing it is so obscure in the long list of config. Let's add it to the key binding page as this is where I think most people will look it up.

Add guide to enter_accept config

---

src/content/docs/guide/installation.mdx

Since the last [release](https://github.com/atuinsh/atuin/releases/tag/v18.4.0) protoc is not required anymore because protox is used.

Remove protoc build requirement info

---

src/content/docs/self-hosting/docker.mdx

The example `ATUIN_DB_URI` uses `@db` as the hostname, but the container was named `postgresql` which led to connection errors:
```
Location:
/app/crates/atuin-server/src/lib.rs:143:10
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:****@db/atuindb" }
Caused by:
Other(error communicating with database: failed to lookup address information: Name or service not known
Caused by:
failed to lookup address information: Name or service not known
Location:
crates/atuin-server-postgres/src/lib.rs:53:39)
```

Fix container name for DB URI

---

src/content/docs/self-hosting/docker.mdx

The current `docker-compose.yml` fails to start today with an error:
> service "atuin" depends on undefined service "postgresql": invalid compose project
This patch modernizes the yml and fixes the link.  Tested on docker compose v2.39.4.

fix docker-compose
